### PR TITLE
Add unstated typing-extensions requirement

### PR DESCRIPTION
**Pull request by tabatkins**

### CODE REVIEW

**Comment by plinss** [comment]
AFAICT there's no dependency on typing-extensions. I just created a bare Python3.6 venv, installed uri_template and was able to run the self test for json_home_client without error.

**Comment by tabatkins** [comment]
There definitely was every time I've run it, both when manually vendored, and when installed from pip in a fresh pyenv. Without Bikeshed's manually-specified typing-extensions, it always dies when importing json_home_client.

**Comment by plinss** [comment]
Ok, I see the problem, it's not json_home_client that's missing typing_extensions, it's widlparser. I'll fix it there.

**Comment by tabatkins** [comment]
oh, lol, sorry about that.

**Pull request closed without merging**
